services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html:rw
      - certs:/etc/nginx/certs
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html:rw
      - certs:/etc/nginx/certs
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env
    command: mysqld --no-default --user=mysql --bind-address=0.0.0.0 --port=3306 --console

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/candriam/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/candriam/data/mariadb

  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/candriam/data/certs

networks:
  inception:
    driver: bridge
